[package]
name = "bilidanmu"
version = "0.1.0"
authors = ["gwy15 <gwy15thu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ "rustls" ]
native-tls = [ "reqwest/native-tls" ]
rustls = [ "reqwest/rustls-tls" ]

[dependencies]
reqwest = { version = "0.11.3", default-features = false }
thiserror = "1.0.24"
log = "0.4.14"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"


[dev-dependencies]
tokio = { version = "1.0", features = ["macros"] }
anyhow = "1.0"
pretty_env_logger = "0.4.0"
